commit_message: '[ci skip]'
files:
  - source: /Shared/data/GninE San Andreas/GninE/locale/en_US/*
    ignore:
      - 'latest_news.png'
      - 'menu_*.png'
    translation: /Shared/data/GninE San Andreas/GninE/locale/%locale_with_underscore%/%original_file_name%
  - source: /Shared/installer/locale/en_US.pot
    translation: /Shared/installer/locale/%locale_with_underscore%.%file_extension%
pull_request_labels:
  - localization
